### PR TITLE
Feature/dropdown field

### PR DESCRIPTION
**Pull request by IgorZiegler**
#42

### CODE REVIEW

**Comment by IgorZiegler** [comment]
Related to https://github.com/systemapic/wu/pull/504

**Comment by IgorZiegler** [comment]
@knutole You have a chance to check it on dev3 =)

**Comment by knutole** [comment]
Looks good, @IgorZiegler. Ready to merge both of these PR's?

**Comment by IgorZiegler** [comment]
@knutole yep

**Pull request merged**
