### PR TITLE
Issue/156

### PR DESCRIPTION
**Pull request by IgorZiegler**
#156
#169

### CODE REVIEW

**Comment by knutole** [comment]
@IgorZiegler ready to merge this?

**Comment by IgorZiegler** [comment]
@knutole I can add it on dev3 an 1 hour and you you will check it=)

**Comment by knutole** [comment]
@IgorZiegler status on this?

**Comment by IgorZiegler** [comment]
@knutole ready to merge

**Comment by knutole** [comment]
Sorry, last comment might be on an old commit :/

**Comment by IgorZiegler** [comment]
I have checkout to this branch on dev3, you could see it [here](https://dev3.systemapic.com/)

**Comment by knutole** [comment]
Looks nice, and seems to work well.

Two issues with fonts on the pre-existing tooltips. The fonts should be Open-Sans, like in the "Shared with 4 people" font:

screen shot 2016-03-09 at 1 24 04 pm
screen shot 2016-03-09 at 1 23 59 pm

**Comment by knutole** [comment]
@IgorZiegler Did you fix the fonts? Then we can merge!

**Pull request merged**
